import sqlite3
connection = sqlite3.connect('data.db')
cursor = connection.cursor()
cursor.execute('CREATE TABLE Student('
               '    ID INTEGER PRIMARY KEY,'
               '    address VARCHAR(100),'
               '    Name VARCHAR(30),'
               '    Year INTEGER'
               ')'
               'CREATE TABLE Building('
               '    address VARCHAR(30) PRIMARY KEY,'
               '    Name VARCHAR(30),'
               '    Abbr VARCHAR(5)
               ')'
               'CREATE TABLE Instructor('
               '    ID INTEGER PRIMARY KEY,'
               '    address VARCHAR(100),'
               '    Name VARCHAR(30),'
               '    Dept VARCHAR(30)'
               ')'
               'CREATE TABLE Located('
               '    Program VARCHAR(30),'
               '    Address VARCHAR(100),'
               '    PRIMARY KEY(Program,Address)'
               ')'
               'CREATE TABLE Room('
               '    Type VARCHAR (20),'
               '    Room_Number INTEGER,'
               '    Address VARCHAR(100),'
               '    PRIMARY KEY(Room_Number, Address)'
               ')'
               'CREATE TABLE Class('
               '    Class_ID CHAR(5),'
               '    DayCode CHAR(5),'
               '    Time INTEGER,'
               '    Course_ID VARCHAR(15),'
               '    PRIMARY KEY(Course_ID, Class_ID)'
               ')'
               'CREATE TABLE Course('
               '    Course_ID VARCHAR(15) PRIMARY KEY,'
               '    Major VARCHAR(30),'
               '    Credit_Hourse INTEGER'
               ')'
               'CREATE TABLE Takes('
               '    ID INTEGER,'
               '    Class_ID CHAR(5),'
               '    Course_ID VARCHAR(15),'
               '    Grade FLOAT,'
               '    PRIMARY KEY(ID, Class_ID, Course_ID'
               ')'
               'CREATE TABLE In('
               '    Course_ID VARCHAR(15),'
               '    Class_ID CHAR(5),'
               '    Room_Number INTEGER,'
               '    Address VARCHAR(100),'
               '    PRIMARY KEY(Course_ID, Class_ID, Room_Number, Address)'
               ')'
               'CREATE TABLE TaughtBy('
               '    ID INTEGER,'
               '    Class_ID CHAR(5),'
               '    Course_ID VARCHAR(15),'
               '    PRIMARY KEY(ID, Class_ID, Course_ID)'
               ')'
               'CREATE TABLE Requires('
               '    ID INTEGER,'
               '    Course_ID VARCHAR(15),'
               '    PRIMARY KEY(ID, Course_ID)'
               ')'
               'CREATE TABLE EmergencyContact('
               '    Phone_Number CHAR(10),'
               '    Address VARCHAR(100),'
               '    Name VARCHAR(30),'
               '    Relation VARCHAR(30),'
               '    ID INTEGER,'
               '    PRIMARY KEY(ID, Name)'
               ')'
               'CREATE TABLE Department('
               '    Program VARCHAR(30) PRIMARY KEY'
               ')'
                )
connection.commit()
cursor.close()